### ISSUE TITLE
Selection box ghost after reset on 2d density map

### ISSUE THREAD

**Issue by birm** [sharmalab/eaglescope#106]
The selection box for 2d density was fixed in #105 , but now there's an edge case where resetting the filters does indeed reset the plot, but not the outline of the previous selection box (until another one is selected).

![image](https://github.com/sharmalab/eaglescope/assets/4951803/405bbe2c-d4fc-4669-b593-0101b7c42d51)

**Comment by MohamedNasser8** [comment]
I can fix it by remove the selected area after the end of the drag as it is in scatter plot.
