### ISSUE TITLE
Title Text Should come from config

### ISSUE THREAD

**Issue by birm** [sharmalab/eaglescope#29]
Right now, the "title text" is a relic from a demo. https://github.com/sharmalab/eaglescope/blob/47ad37a034a72eb2a1f4ca53892e3985cec69e6e/source/index.js#L280  

Instead, read the title from some field in a config file (such as ./config/vis-config.json), with a default value of "eaglescope".

**Comment by anshuman9999** [comment]
Hello, I am interested in taking up this issue

**Comment by birm** [comment]
Any support you may need?

**Comment by anshuman9999** [comment]
I looked at the code and found that the title is being dynamically rendered according to conditions specified in the ` getConfig ` function. Should I take all of those title values and put them in their respective config files? Any help would be greatly appreciated. Thank you.

**Comment by anshuman9999** [comment]
I also thought of changing the comparison operator from double equals to triple equals when comparing the template name. Should I do this too?

**Comment by birm** [comment]
I consider the current [getconfig](https://github.com/sharmalab/eaglescope/blob/061421b0b65589b9262c2f63c73b26879a7fee6e/source/index.js#L36) to be a  temporary solution. Instead some value should be read from somewhere in the config url to populate title.
