### ISSUE TITLE
Download Filtered Data

### ISSUE THREAD

**Issue by birm** [sharmalab/eaglescope#31]
Click a button which downloads the currently filtered data as some format (json? csv? some other thing?)

**Comment by Naseem010** [comment]
Hello @birm Can you please assign me to this issue ?
do you have any specifc method to mention?
here is one method i can think 
1)convert the table data into json format [https://www.aspsnippets.com/Articles/Convert-HTML-Table-data-to-JSON-using-JavaScript.aspx](url)
2)then download the json data using javascript[https://codesandbox.io/s/download-json-file-with-js-p9t1z?from-embed=&file=/index.html](url)

**Comment by malikrafsan** [comment]
Hello @birm , my name is Malik Akbar, a final year computer science student from Indonesia
. I am very excited to contribute to this project for Google Summer of Code (GSoC) 2024. Can you please assign this issue to me?

I will create the functionality first and discuss the UI with you. After I am done with the functionality, I will create the PR. Thank you and looking forward to hearing from you soon!

**Comment by malikrafsan** [comment]
Ahh it turns out this is already implemented
