### ISSUE TITLE
Component version of index.js

### ISSUE THREAD

**Issue by birm** [sharmalab/eaglescope#38]
so that eaglescope can be called as a component of a larger page

**Comment by birm** [comment]
(TCIA recommendation by Joseph Utecht)

**Comment by Naseem010** [comment]
@birm do you mean by managing the versioning of index.js to ensure that changes are tracked and can be properly integrated into the larger codebase?
Can you please elaborate this issues?

**Comment by birm** [comment]
Yes, and this would also presumably include eaglescope taking in config via html arguments like <Eaglescope config=...>
