### ISSUE TITLE
2d Select on "DENSITY_2D" and "scatter" doesn't work right on Firefox

### ISSUE THREAD

**Issue by birm** [sharmalab/eaglescope#91]
For example, 
<img width="968" alt="image" src="https://github.com/sharmalab/eaglescope/assets/4951803/1ebf9a73-01a4-4458-b39c-73268bb2f879">

Click and drag is usually not as expected, and instead outside of the area entirely!

**Comment by birm** [comment]
These work if they're in the top left grid position only. The coordinates are otherwise quite strange!

**Comment by MohamedNasser8** [comment]
I think the problem there are a shift in y axis i tried it plot scatter plot with x axis and y axis so i shoud get a 45 degree plot but 
![scatter](https://github.com/sharmalab/eaglescope/assets/66921605/968a70a7-9370-48ef-8c9e-b7b9c03a8fa7)
There were a shift so i fixed it by removing it.
![scatter2](https://github.com/sharmalab/eaglescope/assets/66921605/8ccb51a1-f3cb-47ac-a2d3-2816ae95c625)

**Comment by birm** [comment]
cool! Were you able to determine if that fixed the click and drag brush events?

**Comment by MohamedNasser8** [comment]
Yes, I fixed it for scattering plot
I will merge and solve it for Density Chart

**Comment by birm** [comment]
For added context, this seems to be a firefox issue; works ok on chrome.

**Comment by MohamedNasser8** [comment]
I think i made it better to visualize.
I have already made a PR.
